name: Bug Report
description: Report an error or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug, including a minimal reproducible example.
        If we cannot reproduce the bug, it is unlikely that we will be able to help you.
    validations:
      required: true
